"""empty message

Revision ID: 0c82fd96b58a
Revises: 
Create Date: 2025-01-01 11:02:05.740289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c82fd96b58a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column('favorite_food')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column(sa.Column('favorite_food', sa.VARCHAR(length=200), nullable=True))

    # ### end Alembic commands ###
