"""empty message

Revision ID: e1544eb049f6
Revises: 7eba3305d664
Create Date: 2025-01-25 12:29:24.855080

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import MetaData
from flask import Flask
from flask_sqlalchemy import SQLAlchemy

# revision identifiers, used by Alembic.
revision = 'e1544eb049f6'
down_revision = '7eba3305d664'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_users')
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poster_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['poster_id'], ['id'])
        batch_op.drop_column('author')

    # ### end Alembic commands ###
naming_convention = {
    "ix": 'ix_%(column_0_label)s',
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(column_0_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s"
}
#app = Flask(__name__)

#metadata=MetaData(naming_convention=naming_convention)
#db=SQLAlchemy(app,metadata=metadata)
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None,naming_convention=naming_convention) as batch_op:
        batch_op.add_column(sa.Column('author', sa.VARCHAR(length=255), nullable=True))
        #batch_op.drop_constraint('fk_test_user_id_user', type_='foreignkey')
        batch_op.drop_column('poster_id')

    op.create_table('_alembic_tmp_users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=120), nullable=True),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('date_added', sa.DATETIME(), nullable=True),
    sa.Column('favorite_food', sa.VARCHAR(length=150), nullable=True),
    sa.Column('username', sa.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###
